name: "Tests"
on: [push, pull_request]

jobs:
  jest-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Install Dependencies
        run: npm ci
      - name: Test Build
        run: npm run test_build
      - name: Checking format
        if: matrix.os == 'ubuntu-latest'
        run: npm run format-check
      - name: Linting code
        if: matrix.os == 'ubuntu-latest'
        run: npm run lint
      - name: Running jest tests
        run: npm test
      - name: Codecov Upload
        continue-on-error: true
        uses: codecov/codecov-action@v2
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./coverage/lcov.info

  test-integration:
    runs-on: ${{ matrix.os }}
    needs: [jest-tests]
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm ci
      - name: Build index.js
        run: npm run package
      - uses: ./
        with:
          dummy-input: "bar"
